### ISSUE TITLE
Exercise implementation tracker

### ISSUE THREAD

**Issue by gvrooyen** [exercism/odin#26]
The maintainers for the Odin track (@glennj  and @rmonnet) are in the process of setting up a new exercise wish-list to replace this one. We are working hard to get the Odin track up and running.

For now if you are on the list below and are not interested anymore, please let us know so we can re-assign the exercise. If you have questions or need help, please reach us on the forum [Odin Track topic](https://forum.exercism.org/t/new-track-odin-programming-language/7379/48) first.

Do not start working on new exercises without discussing it on the forum [Odin Track topic](https://forum.exercism.org/t/new-track-odin-programming-language/7379/48) first. We do have a new candidate list that will be available soon.

## CLAIMED
- [x] Collatz Conjecture (`collatz-conjecture`) -@gvrooyen
- [x] Queen Attack (`queen-attack`) - @gvrooyen
- [x] Darts (`darts`) - @gvrooyen
- [x] Resistor Color Duo (`resistor-color-duo`) - @gvrooyen
- [x] Hamming (`hamming`) - @gvrooyen
- [x] Space Age (`space-age`) - @gvrooyen
- [x] Binary (`binary`) - @pjlast
- [x] RNA Transcription (`rna-transcription`) - @gvrooyen
- [x] Eliud’s Eggs (`eliuds-eggs`) - @gvrooyen
- [x] Raindrops (`raindrops`) - @gvrooyen
- [x] D&D Character (`dnd-character`) - @gvrooyen
- [x] Perfect Numbers (`perfect-numbers`) - @gvrooyen
- [x] Pangram (`pangram`) - @hucancode 
- [x] Resistor Color Trio (`resistor-color-trio`) - @hucancode 
- [x] Armstrong Numbers (`armstrong-numbers`) - @hucancode 
- [x] Food Chain (`food-chain`) - @hucancode   
- [x] High Scores (`high-scores`) - @rmonnet 

## MERGED
- [x] Hello World (`hello-world`)
- [x] Difference of Squares (`difference-of-squares`)
- [x] Grains (`grains`)
- [x] Leap (`leap`)
- [x] Resistor Color (`resistor-color`)
- [x] Two Fer (`two-fer`) - @BNAndras

**Comment by hucancode** [comment]
I would like to work on Robot Names, Armstrong Numbers, Pangram
